# Generated by Django 5.2 on 2025-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='release_date',
        ),
        migrations.AddField(
            model_name='gadget',
            name='category',
            field=models.CharField(default='smartphone', max_length=50),
        ),
    ]
